environment:
        CIRRUS_CLONE_DEPTH: 1

container:
        dockerfile: Dockerfile
        # 2 CPU/4GB RAM by default
        # community cluster limits:
        # CPUs: 8
        # RAM: 24 GB
        cpu: 4
        memory: 8G

gdc_task:
        # 2 hours is a hard limit for community cluster.
        timeout_in: 120m
        clone_script: git clone --branch=master-ci --depth=1 https://github.com/W-joe/gcc /tmp/cirrus-ci-build
        env_script:
                - pwd
                - env
                - ls -l
        setup_script: ./buildci.sh setup
        build_script: ./buildci.sh build
        test_script: ./buildci.sh testsuite


unittest_task:
        # 2 hours is a hard limit for community cluster.
        timeout_in: 120m
        clone_script: git clone --branch=master-ci --depth=1 https://github.com/W-joe/gcc /tmp/cirrus-ci-build
        env_script:
                - pwd
                - env
                - ls -l
        setup_script: ./buildci.sh setup
        build_script: ./buildci.sh build
        test_script: ./buildci.sh unittests


