environment:
        CIRRUS_CLONE_DEPTH: 1

# Global defaults
container:
        dockerfile: Dockerfile
        # 2 CPU/4GB RAM by default
        # community cluster limits:
        # CPUs: 8
        # RAM: 24 GB
        cpu: 4
        memory: 10G

task:
        # 2 hours is a hard limit for community cluster.
        timeout_in: 120m
        clone_script: git clone --branch=master-ci --depth=1 https://github.com/W-joe/gcc /tmp/cirrus-ci-build
        env_script:
                - pwd
                - env
                - ls -l
        matrix:
                - name: GDC
                  container:
                          matrix:
                                  - dockerfile: Dockerfile
                                  # TODO: add containers for different platforms
                  setup_script: ./buildci.sh setup
                  build_script: ./buildci.sh build
                  test_script: ./buildci.sh testsuite
                  on_failure:
                          log_script: ./buildci.sh print_gdc_summary


task:
        # 2 hours is a hard limit for community cluster.
        timeout_in: 120m
        clone_script: git clone --branch=master-ci --depth=1 https://github.com/W-joe/gcc /tmp/cirrus-ci-build
        env_script:
                - pwd
                - env
                - ls -l
        matrix:
                - name: Unittest
                  container:
                          matrix:
                                  - dockerfile: Dockerfile
                                  # TODO: add containers for different platforms
                  setup_script: ./buildci.sh setup
                  build_script: ./buildci.sh build
                  test_script: ./buildci.sh unittests
                  on_failure:
                          log_script: ./buildci.sh print_libphobos_summary

                - name: Package
                  depends_on:
                          - Unittest
                  install_script: ./buildci.sh build_package

